In [10]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [95]:
import lightning as L

from lightning import LightningDataModule

In [96]:
import polars as pl

In [97]:
from src.data.bats_datamodule import BatsDataModule

In [106]:
data = BatsDataModule(
    data_dir="/Users/ivanr/diploma/animal-communication-source-separation/datasets/egyptian_fruit_bats",
    audio_fname="audio",
    annotations_fname="annotations.csv",
)

In [107]:
data.setup()

In [108]:
train = data.train_dataloader()

In [109]:
len(train)

125

In [ ]:
df.with_columns(
    pl.col("Color").rank("dense") - 1
)

In [110]:
for x, y in train:
    print(x.shape, y.shape)
    print(y)
    break

torch.Size([64, 3, 256, 257]) torch.Size([64])
tensor([220, 111, 215, 220, 226, 215, 216, 216, 228, 216, 231, 230, 111, 210,
        231, 211, 111, 216, 111, 231, 210, 220, 231, 216, 210, 220, 226, 216,
        211, 230, 210, 228, 226, 216, 220, 111, 228, 215, 228, 210, 111, 215,
        216, 230, 226, 215, 216, 211, 230, 231, 230, 230, 228, 226, 216, 211,
        228, 220, 226, 215, 111, 228, 230, 210])

In [72]:
torchaudio.load("/Users/ivanr/diploma/animal-communication-source-separation/datasets/egyptian_fruit_bats/audio/10056.wav")[0].shape

torch.Size([1, 410447])

In [111]:
annotations = pl.read_csv("/Users/ivanr/diploma/animal-communication-source-separation/datasets/egyptian_fruit_bats/annotations.csv")

In [121]:
annotations.select(
    [
        pl.col("Emitter").rank("dense") - 1
    ]
).to_torch().ravel()

tensor([4, 3, 4,  ..., 0, 0, 0])

In [112]:
annotations

shape: (10_000, 2)
┌─────────┬───────────┐
│ Emitter ┆ File Name │
│ ---     ┆ ---       │
│ i64     ┆ str       │
╞═════════╪═══════════╡
│ 216     ┆ 69809.wav │
│ 215     ┆ 71889.wav │
│ 216     ┆ 46690.wav │
│ 230     ┆ 85411.wav │
│ 215     ┆ 45609.wav │
│ …       ┆ …         │
│ 111     ┆ 33297.wav │
│ 111     ┆ 26880.wav │
│ 111     ┆ 24407.wav │
│ 111     ┆ 22549.wav │
│ 111     ┆ 15217.wav │
└─────────┴───────────┘

In [8]:
annotations.select(
    [
        pl.col("Emitter").unique_counts(),
    ]
)

shape: (10, 1)
┌─────────┐
│ Emitter │
│ ---     │
│ u32     │
╞═════════╡
│ 1000    │
│ 1000    │
│ 1000    │
│ 1000    │
│ 1000    │
│ 1000    │
│ 1000    │
│ 1000    │
│ 1000    │
│ 1000    │
└─────────┘